
local M = {}

function M.build(p)
  local groups = {
    Normal = { fg = p.fg_main, bg = p.bg_main },
    NormalNC = { fg = p.fg_main, bg = p.bg_main },
    Cursor = { fg = p.bg_main, bg = p.cursor },
    CursorLine = { bg = p.bg_shadow_subtle },
    CursorColumn = { bg = p.bg_shadow_subtle },
    ColorColumn = { bg = p.bg_shadow_subtle },
    LineNr = { fg = p.fg_shadow_subtle },
    CursorLineNr = { fg = p.fg_main, bold = true },
    SignColumn = { fg = p.fg_shadow_subtle, bg = p.bg_main },
    EndOfBuffer = { fg = p.bg_main },
    VertSplit = { fg = p.border },
    WinSeparator = { fg = p.border },
    StatusLine = { fg = p.fg_main, bg = p.bg_shadow_subtle },
    StatusLineNC = { fg = p.fg_shadow_subtle, bg = p.bg_shadow_subtle },
    TabLine = { fg = p.fg_shadow_subtle, bg = p.bg_shadow_subtle },
    TabLineSel = { fg = p.fg_main, bg = p.bg_main, bold = true },
    TabLineFill = { fg = p.fg_shadow_subtle, bg = p.bg_shadow_subtle },
    Pmenu = { fg = p.fg_shadow_subtle, bg = p.bg_shadow_subtle },
    PmenuSel = { fg = p.fg_main, bg = p.bg_accent },
    PmenuSbar = { bg = p.bg_shadow_subtle },
    PmenuThumb = { bg = p.bg_shadow_intense },
    Visual = { bg = p.bg_accent },
    Search = { fg = p.fg_main, bg = p.bg_shadow_intense },
    IncSearch = { fg = p.bg_main, bg = p.fg_shadow_intense },
    MatchParen = { fg = p.fg_shadow_intense, bg = p.bg_shadow_subtle, bold = true },
    Folded = { fg = p.fg_shadow_subtle, bg = p.bg_shadow_subtle },
    FoldColumn = { fg = p.fg_shadow_subtle, bg = p.bg_main },
    Title = { fg = p.fg_shadow_intense, bold = true },
    Directory = { fg = p.fg_accent },
    NonText = { fg = p.fg_shadow_subtle },
    Whitespace = { fg = p.fg_shadow_subtle },
    SpecialKey = { fg = p.fg_shadow_subtle },
    ModeMsg = { fg = p.fg_shadow_intense, bold = true },
    MoreMsg = { fg = p.fg_shadow_intense, bold = true },
    WarningMsg = { fg = p.fg_yellow, bold = true },
    ErrorMsg = { fg = p.fg_red, bold = true },
    Question = { fg = p.fg_shadow_intense, bold = true },

    Comment = { fg = p.fg_accent, italic = true },
    Constant = { fg = p.fg_main },
    String = { fg = p.fg_shadow_subtle, italic = true },
    Character = { fg = p.fg_shadow_subtle },
    Number = { fg = p.fg_main },
    Boolean = { fg = p.fg_main },
    Float = { fg = p.fg_main },
    Identifier = { fg = p.fg_main },
    Function = { fg = p.fg_shadow_intense, bold = true },
    Statement = { fg = p.fg_shadow_subtle, bold = true },
    Conditional = { fg = p.fg_shadow_subtle, bold = true },
    Repeat = { fg = p.fg_shadow_subtle, bold = true },
    Label = { fg = p.fg_shadow_subtle, bold = true },
    Operator = { fg = p.fg_shadow_subtle, bold = true },
    Keyword = { fg = p.fg_shadow_subtle, bold = true },
    Exception = { fg = p.fg_shadow_subtle, bold = true },
    PreProc = { fg = p.fg_shadow_subtle, bold = true },
    Include = { fg = p.fg_shadow_subtle, bold = true },
    Define = { fg = p.fg_shadow_subtle, bold = true },
    Macro = { fg = p.fg_shadow_subtle, bold = true },
    PreCondit = { fg = p.fg_shadow_subtle, bold = true },
    Type = { fg = p.fg_shadow_subtle, bold = true, italic = true },
    StorageClass = { fg = p.fg_shadow_subtle, bold = true, italic = true },
    Structure = { fg = p.fg_shadow_subtle, bold = true, italic = true },
    Typedef = { fg = p.fg_shadow_subtle, bold = true, italic = true },
    Special = { fg = p.fg_main },
    SpecialChar = { fg = p.fg_shadow_subtle },
    Tag = { fg = p.fg_shadow_subtle },
    Delimiter = { fg = p.fg_shadow_subtle },
    SpecialComment = { fg = p.fg_shadow_subtle, italic = true },
    Debug = { fg = p.fg_shadow_subtle },
    Underlined = { fg = p.fg_accent, underline = true },
    Ignore = { fg = p.fg_shadow_subtle },
    Error = { fg = p.fg_red, bold = true },
    Todo = { fg = p.fg_yellow, bold = true },

    DiffAdd = { fg = p.fg_neutral, bg = p.bg_green },
    DiffChange = { fg = p.fg_neutral, bg = p.bg_yellow },
    DiffDelete = { fg = p.fg_neutral, bg = p.bg_red },
    DiffText = { fg = p.fg_main, bg = p.bg_shadow_intense, bold = true },

    DiagnosticError = { fg = p.fg_red, bold = true },
    DiagnosticWarn = { fg = p.fg_yellow, bold = true },
    DiagnosticInfo = { fg = p.fg_cyan, bold = true },
    DiagnosticHint = { fg = p.fg_green, bold = true },
    DiagnosticUnderlineError = { undercurl = true, sp = p.fg_red },
    DiagnosticUnderlineWarn = { undercurl = true, sp = p.fg_yellow },
    DiagnosticUnderlineInfo = { undercurl = true, sp = p.fg_cyan },
    DiagnosticUnderlineHint = { undercurl = true, sp = p.fg_green },

    LspReferenceText = { bg = p.bg_shadow_subtle },
    LspReferenceRead = { bg = p.bg_shadow_subtle },
    LspReferenceWrite = { bg = p.bg_shadow_subtle },
    LspInlayHint = { fg = p.fg_shadow_subtle, bg = p.bg_shadow_subtle },

    ["@comment"] = { fg = p.fg_accent, italic = true },
    ["@string"] = { fg = p.fg_shadow_subtle, italic = true },
    ["@number"] = { fg = p.fg_main },
    ["@boolean"] = { fg = p.fg_main },
    ["@function"] = { fg = p.fg_shadow_intense, bold = true },
    ["@function.builtin"] = { fg = p.fg_shadow_subtle, bold = true, italic = true },
    ["@keyword"] = { fg = p.fg_shadow_subtle, bold = true },
    ["@keyword.return"] = { fg = p.fg_shadow_subtle, bold = true },
    ["@type"] = { fg = p.fg_shadow_subtle, bold = true, italic = true },
    ["@type.builtin"] = { fg = p.fg_shadow_subtle, italic = true },
    ["@variable"] = { fg = p.fg_main, italic = true },
    ["@variable.builtin"] = { fg = p.fg_shadow_subtle, italic = true },
    ["@constant"] = { fg = p.fg_main },
    ["@constant.builtin"] = { fg = p.fg_shadow_subtle },
    ["@punctuation.delimiter"] = { fg = p.fg_shadow_subtle },
    ["@punctuation.bracket"] = { fg = p.fg_shadow_subtle },
    ["@operator"] = { fg = p.fg_shadow_subtle, bold = true },
    ["@tag"] = { fg = p.fg_shadow_subtle },
    ["@tag.attribute"] = { fg = p.fg_shadow_subtle },
    ["@tag.delimiter"] = { fg = p.fg_shadow_subtle },
    ["@property"] = { fg = p.fg_shadow_subtle },
    ["@field"] = { fg = p.fg_shadow_subtle },
    ["@constructor"] = { fg = p.fg_shadow_subtle, bold = true },
    ["@label"] = { fg = p.fg_shadow_subtle, bold = true },
    ["@conditional"] = { fg = p.fg_shadow_subtle, bold = true },
    ["@repeat"] = { fg = p.fg_shadow_subtle, bold = true },
    ["@exception"] = { fg = p.fg_shadow_subtle, bold = true },
  }

  return groups
end

return M
