background #2a2f48
foreground #dde0f8
cursor #e08ca0
cursor_text_color #2a2f48
selection_background #424381
selection_foreground #dde0f8
color0 #3c3e55
color1 #eca28f
color2 #a0d0ba
color3 #c0b080
color4 #9fbfe7
color5 #e9acbf
color6 #a0c0d0
color7 #dde0f8
color8 #aea7c3
color9 #eca28f
color10 #a0d0ba
color11 #c0b080
color12 #9fbfe7
color13 #e9acbf
color14 #a0c0d0
color15 #dde0f8
