background #383035
foreground #e0d5b7
cursor #94d0eb
cursor_text_color #383035
selection_background #3d5e57
selection_foreground #e0d5b7
color0 #484040
color1 #eca28f
color2 #b9d0aa
color3 #c0b060
color4 #9fbfe7
color5 #e9acbf
color6 #a0c0d0
color7 #e0d5b7
color8 #afa497
color9 #eca28f
color10 #b9d0aa
color11 #c0b060
color12 #9fbfe7
color13 #e9acbf
color14 #a0c0d0
color15 #e0d5b7
