background #282420
foreground #f5ceb0
cursor #ef7839
cursor_text_color #282420
selection_background #7c362c
selection_foreground #f5ceb0
color0 #40332b
color1 #eca27f
color2 #b9d08a
color3 #c5ba80
color4 #9fbfe7
color5 #e9acbf
color6 #a0c0d0
color7 #f5ceb0
color8 #afa497
color9 #eca27f
color10 #b9d08a
color11 #c5ba80
color12 #9fbfe7
color13 #e9acbf
color14 #a0c0d0
color15 #f5ceb0
