background #221832
foreground #e2d7e7
cursor #c070d0
cursor_text_color #221832
selection_background #5e4170
selection_foreground #e2d7e7
color0 #302f3c
color1 #eca28f
color2 #b9d0aa
color3 #c0b080
color4 #9fbfe7
color5 #e9acbf
color6 #a0c0d0
color7 #e2d7e7
color8 #a694b1
color9 #eca28f
color10 #b9d0aa
color11 #c0b080
color12 #9fbfe7
color13 #e9acbf
color14 #a0c0d0
color15 #e2d7e7
