background #44312e
foreground #e7d0bf
cursor #74e0ab
cursor_text_color #44312e
selection_background #7e462c
selection_foreground #e7d0bf
color0 #584040
color1 #eca28f
color2 #b9d0aa
color3 #c0b060
color4 #9fbfe7
color5 #e9acbf
color6 #a0c0d0
color7 #e7d0bf
color8 #9aa3af
color9 #eca28f
color10 #b9d0aa
color11 #c0b060
color12 #9fbfe7
color13 #e9acbf
color14 #a0c0d0
color15 #e7d0bf
