background #303f2d
foreground #d0e2c8
cursor #c0a27a
cursor_text_color #303f2d
selection_background #70523a
selection_foreground #d0e2c8
color0 #40503d
color1 #e8a28f
color2 #82cc9f
color3 #c4b980
color4 #8fbae5
color5 #e9acbf
color6 #a0c0d0
color7 #d0e2c8
color8 #bcbeaf
color9 #e8a28f
color10 #82cc9f
color11 #c4b980
color12 #8fbae5
color13 #e9acbf
color14 #a0c0d0
color15 #d0e2c8
