background #2a283d
foreground #edf0f8
cursor #99ddee
cursor_text_color #2a283d
selection_background #496278
selection_foreground #edf0f8
color0 #3a3c4c
color1 #eca28f
color2 #a0d0ba
color3 #c0b080
color4 #9fbfe7
color5 #e9acbf
color6 #a0c0d0
color7 #edf0f8
color8 #aea6b8
color9 #eca28f
color10 #a0d0ba
color11 #c0b080
color12 #9fbfe7
color13 #e9acbf
color14 #a0c0d0
color15 #edf0f8
