background #181818
foreground #e7e7e7
cursor #eeddbb
cursor_text_color #181818
selection_background #505050
selection_foreground #e7e7e7
color0 #2f2f2f
color1 #eca28f
color2 #b9d0aa
color3 #c0b080
color4 #9fbfe7
color5 #e9acbf
color6 #a0c0d0
color7 #e7e7e7
color8 #969696
color9 #eca28f
color10 #b9d0aa
color11 #c0b080
color12 #9fbfe7
color13 #e9acbf
color14 #a0c0d0
color15 #e7e7e7
